// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKdW-X1-vg2ySgBansqfY_lxGHWOmnZd0',
    appId: '1:816399946622:web:86ba19e2bc6090a950192f',
    messagingSenderId: '816399946622',
    projectId: 'e-commerce-app-5795a',
    authDomain: 'e-commerce-app-5795a.firebaseapp.com',
    storageBucket: 'e-commerce-app-5795a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIHIPR8FwSzoDu87jOO24EX-yRyWGKEY0',
    appId: '1:816399946622:android:0c31c55e4df6804150192f',
    messagingSenderId: '816399946622',
    projectId: 'e-commerce-app-5795a',
    storageBucket: 'e-commerce-app-5795a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGfBqL5HPpLTw06V2H93nyohwSyA6R7TI',
    appId: '1:816399946622:ios:83f480c6a95a1f3550192f',
    messagingSenderId: '816399946622',
    projectId: 'e-commerce-app-5795a',
    storageBucket: 'e-commerce-app-5795a.firebasestorage.app',
    androidClientId: '816399946622-bdcgmibi87f2odqdjuqr5akg5th5djtb.apps.googleusercontent.com',
    iosClientId: '816399946622-ejvjp74b1rafo42k4kic9uve082fsvdr.apps.googleusercontent.com',
    iosBundleId: 'com.example.eApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGfBqL5HPpLTw06V2H93nyohwSyA6R7TI',
    appId: '1:816399946622:ios:83f480c6a95a1f3550192f',
    messagingSenderId: '816399946622',
    projectId: 'e-commerce-app-5795a',
    storageBucket: 'e-commerce-app-5795a.firebasestorage.app',
    androidClientId: '816399946622-bdcgmibi87f2odqdjuqr5akg5th5djtb.apps.googleusercontent.com',
    iosClientId: '816399946622-ejvjp74b1rafo42k4kic9uve082fsvdr.apps.googleusercontent.com',
    iosBundleId: 'com.example.eApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKdW-X1-vg2ySgBansqfY_lxGHWOmnZd0',
    appId: '1:816399946622:web:5cc3652c69ee3f8b50192f',
    messagingSenderId: '816399946622',
    projectId: 'e-commerce-app-5795a',
    authDomain: 'e-commerce-app-5795a.firebaseapp.com',
    storageBucket: 'e-commerce-app-5795a.firebasestorage.app',
  );

}